package:
  name: pangalactic.core
  version: "4.1.dev12"

source:
        path: C:\Users\swaterbu\clones\pangalactic.core

requirements:
  build:
    - python {{PY_VER}}
    - setuptools

  run:
    - louie
    - openpyxl
    - pint
    - python {{PY_VER}}
    - python-dateutil
    - pytz
    - ruamel_yaml
    - sqlalchemy <2.0
    - tzlocal
    - unidecode
    - xlrd
    - xlwt
    - xlsxwriter
    # locally created conda packages
    - rdflib

about:
  # home: https://pangalactic.us
  license: NASA
  # license_file: LICENSE

