package:
  name: pangalactic.core
  version: "0.1.dev95"

source:
  path: # [path to source]

requirements:
  build:
    - python
    - setuptools

  run:
    - python >=2.7
    - pytz
    - ruamel_yaml <=0.15
    - service_identity
    - sqlalchemy
    - twisted
    - tzlocal
    - unidecode
    - xlrd
    - xlwt
    - xlsxwriter
    - zope
    - zope.interface
    # -----------------------------------------------------
    # packages installed from local repo (copied)
    - numpy >=1.13.3
    # service_identity (reqd. by autobahn)
    # txaio (reqd. by autobahn)
    # -----------------------------------------------------
    # packages installed from local repo (locally built)
    - inflect
    # - louie [not used now but might be in the future]
    - pint
    - python-dateutil
    - rdflib
    # - isodate (required by rdflib)
    # -----------------------------------------------------

# test:
  # imports:
    # - sometestpackage

about:
  # home: https://pangalactic.us
  license: NASA
  # license_file: LICENSE

