"""
Tests of the extract (serialization) function
"""
from pangalactic.test.utils4test import gen_linked_test_objects, DTSTAMP
from pangalactic.meta.registry import PanGalacticRegistry as R
from pangalactic.utils.datetimes import dtstamp, dt2str
from twisted.trial import unittest

# must explicitly set 'home' for testing in case env var PANGALAXIAN is set
r = R(home='pangalaxian_test', force_new_core=1)
dtiso = DTSTAMP.isoformat('.')
dtstr = dt2str(DTSTAMP)
test_objects = gen_linked_test_objects('TFE', r)

class ExtractTests(unittest.TestCase):

    def test_01_extract_linked_objects(self):
        """CASE:  [r.extract(o) for o in Objects]"""
        result = [r.extract(o) for o in test_objects]
        expected = [
            {'comment': u'',
             'create_datetime': dtstr,
             'creator': 'test:fester.bestertester',
             'description': u'',
             'id': 'model/p21',
             'id_ns': 'test',
             'media_subtype': u'p21',
             'media_type': u'model',
             'meta_id': 'Mime',
             'mod_datetime': dtstr,
             'modifier': 'test:fester.bestertester',
             'name': u'',
             'oid': 'oid-SMime-0-' + dtiso,
             'owner': 'test:fester.bestertester',
             'record_create_datetime': dtstr,
             'record_creator': 'test:fester.bestertester',
             'record_mod_datetime': dtstr,
             'record_modifier': 'test:fester.bestertester',
             'record_owner': 'test:fester.bestertester',
             'security_mask': 0,
             'url': ''},
            {'comment': u'',
             'create_datetime': dtstr,
             'creator': 'test:fester.bestertester',
             'description': u'',
             'first_name': u'',
             'id': 'fester.bestertester',
             'id_ns': 'test',
             'last_name': u'',
             'meta_id': 'Person',
             'mi_or_name': u'',
             'mod_datetime': dtstr,
             'modifier': 'test:fester.bestertester',
             'name': u'Fester Bestertester',
             'oid': 'oid-SPerson-0-' + dtiso,
             'owner': 'test:fester.bestertester',
             'record_create_datetime': dtstr,
             'record_creator': 'test:fester.bestertester',
             'record_mod_datetime': dtstr,
             'record_modifier': 'test:fester.bestertester',
             'record_owner': 'test:fester.bestertester',
             'security_mask': 0,
             'url': ''},
            {'bytes': 42000,
             'comment': u'',
             'create_datetime': dtstr,
             'creator': 'test:fester.bestertester',
             'description': u'',
             'file_role': u'',
             'file_sequence': 0,
             'file_sequence_context': u'',
             'id': 'file-1.TFE.' + dtiso,
             'id_ns': 'test',
             'is_secured': True,
             'meta_id': 'FileLink',
             'mime_type': 'oid-SMime-0-' + dtiso,
             'mod_datetime': dtstr,
             'modifier': 'test:fester.bestertester',
             'name': u'',
             'oid': 'oid-SFileLink-0-' + dtiso,
             'owner': 'test:fester.bestertester',
             'record_create_datetime': dtstr,
             'record_creator': 'test:fester.bestertester',
             'record_mod_datetime': dtstr,
             'record_modifier': 'test:fester.bestertester',
             'record_owner': 'test:fester.bestertester',
             'security_mask': 0,
             'url': '',
             'user_file_name': u'thingy.p21'},
            {'bytes': 12345,
             'comment': u'',
             'create_datetime': dtstr,
             'creator': 'test:fester.bestertester',
             'description': u'',
             'file_role': u'',
             'file_sequence': 0,
             'file_sequence_context': u'',
             'id': 'file-2.TFE.' + dtiso,
             'id_ns': 'test',
             'is_secured': True,
             'meta_id': 'FileLink',
             'mime_type': 'oid-SMime-0-' + dtiso,
             'mod_datetime': dtstr,
             'modifier': 'test:fester.bestertester',
             'name': u'',
             'oid': 'oid-SFileLink-1-' + dtiso,
             'owner': 'test:fester.bestertester',
             'record_create_datetime': dtstr,
             'record_creator': 'test:fester.bestertester',
             'record_mod_datetime': dtstr,
             'record_modifier': 'test:fester.bestertester',
             'record_owner': 'test:fester.bestertester',
             'security_mask': 0,
             'url': '',
             'user_file_name': u'thingy_libpart1.p21'},
            {'comment': u'',
             'create_datetime': dtstr,
             'creator': 'test:fester.bestertester',
             'description': u'',
             'files': ['oid-SFileLink-0-' + dtiso,
                       'oid-SFileLink-1-' + dtiso],
             'id': 'representation-1.TFE.' + dtiso,
             'id_ns': 'test',
             'is_composable': True,
             'is_generable': True,
             'is_object_source': True,
             'meta_id': 'Representation',
             'mod_datetime': dtstr,
             'modifier': 'test:fester.bestertester',
             'name': u'',
             'oid': 'oid-SRepresentation-0-' + dtiso,
             'owner': 'test:fester.bestertester',
             'record_create_datetime': dtstr,
             'record_creator': 'test:fester.bestertester',
             'record_mod_datetime': dtstr,
             'record_modifier': 'test:fester.bestertester',
             'record_owner': 'test:fester.bestertester',
             'rep_purpose': u'exchange',
             'security_mask': 0,
             'url': ''},
            {'comment': u'',
             'create_datetime': dtstr,
             'creator': 'test:fester.bestertester',
             'description': u'',
             'id': 'TEST',
             'id_ns': 'test',
             'meta_id': 'Project',
             'mod_datetime': dtstr,
             'modifier': 'test:fester.bestertester',
             'name': u'The Testing Project',
             'oid': 'oid-SProject-0-' + dtiso,
             'owner': 'test:fester.bestertester',
             'record_create_datetime': dtstr,
             'record_creator': 'test:fester.bestertester',
             'record_mod_datetime': dtstr,
             'record_modifier': 'test:fester.bestertester',
             'record_owner': 'test:fester.bestertester',
             'security_mask': 0,
             'url': ''},
            {'base_id': '',
             'cm_authority': 'oid-SProject-0-' + dtiso,
             'comment': u'',
             'create_datetime': dtstr,
             'creator': 'test:fester.bestertester',
             'description': u'',
             'fsc_code': u'',
             'id': 'Part-1.TFE.' + dtiso,
             'id_ns': 'test',
             'iteration': 0,
             'meta_id': 'Part',
             'mod_datetime': dtstr,
             'modifier': 'test:fester.bestertester',
             'name': u'Part 1A',
             'oid': 'oid-SPart-0-' + dtiso,
             'owner': 'test:fester.bestertester',
             'part_number_aliases': u'',
             'part_number_drawing': u'',
             'part_number_generic': u'',
             'part_number_mfr': u'',
             'part_number_model': u'',
             'part_number_nsn': u'',
             'part_number_spec': u'',
             'record_create_datetime': dtstr,
             'record_creator': 'test:fester.bestertester',
             'record_mod_datetime': dtstr,
             'record_modifier': 'test:fester.bestertester',
             'record_owner': 'test:fester.bestertester',
             'security_mask': 0,
             'specification': u'',
             'specification_military': u'',
             'specification_screening': u'',
             'url': '',
             'version': 'A',
             'version_sequence': 0},
            {'base_id': '',
             'cm_authority': 'oid-SProject-0-' + dtiso,
             'comment': u'',
             'create_datetime': dtstr,
             'creator': 'test:fester.bestertester',
             'description': u'',
             'fsc_code': u'',
             'id': 'Part-2.TFE.' + dtiso,
             'id_ns': 'test',
             'iteration': 1,
             'meta_id': 'Part',
             'mod_datetime': dtstr,
             'modifier': 'test:fester.bestertester',
             'name': u'Part 1B',
             'oid': 'oid-SPart-1-' + dtiso,
             'owner': 'test:fester.bestertester',
             'part_number_aliases': u'',
             'part_number_drawing': u'',
             'part_number_generic': u'',
             'part_number_mfr': u'',
             'part_number_model': u'',
             'part_number_nsn': u'',
             'part_number_spec': u'',
             'record_create_datetime': dtstr,
             'record_creator': 'test:fester.bestertester',
             'record_mod_datetime': dtstr,
             'record_modifier': 'test:fester.bestertester',
             'record_owner': 'test:fester.bestertester',
             'security_mask': 0,
             'specification': u'',
             'specification_military': u'',
             'specification_screening': u'',
             'url': '',
             'version': 'B',
             'version_sequence': 0},
            {'base_id': 'FX-CAP',
             'cm_authority': 'sandbox:H2G2',
             'comment': u'',
             'create_datetime': dtstr,
             'creator': 'test:fester.bestertester',
             'description': u'',
             'fsc_code': u'',
             'id': 'FX CAP.TFE.' + dtiso,
             'id_ns': 'test',
             'iteration': 0,
             'meta_id': 'Part',
             'mod_datetime': dtstr,
             'modifier': 'test:fester.bestertester',
             'name': u'Flux Capacitor',
             'oid': 'oid-SPart-2-' + dtiso,
             'owner': 'test:fester.bestertester',
             'part_number_aliases': u'',
             'part_number_drawing': u'',
             'part_number_generic': u'',
             'part_number_mfr': u'',
             'part_number_model': u'',
             'part_number_nsn': u'',
             'part_number_spec': u'',
             'record_create_datetime': dtstr,
             'record_creator': 'test:fester.bestertester',
             'record_mod_datetime': dtstr,
             'record_modifier': 'test:fester.bestertester',
             'record_owner': 'test:fester.bestertester',
             'security_mask': 0,
             'specification': u'',
             'specification_military': u'',
             'specification_screening': u'',
             'url': '',
             'version': 'working',
             'version_sequence': 0},
            {'base_id': '',
             'cm_authority': 'oid-SProject-0-' + dtiso,
             'comment': u'',
             'create_datetime': dtstr,
             'creator': 'test:fester.bestertester',
             'definition_context': u'',
             'description': u'',
             'frame_of_reference': u'',
             'id': 'Mechanical-Model-1.TFE.' + dtiso,
             'id_ns': 'test',
             'iteration': 0,
             'life_cycle_stage': u'',
             'meta_id': 'Model',
             'mod_datetime': dtstr,
             'modifier': 'test:fester.bestertester',
             'name': u'TFE-Model-1, Version A',
             'oid': 'oid-SModel-0-' + dtiso,
             'owner': 'test:fester.bestertester',
             'record_create_datetime': dtstr,
             'record_creator': 'test:fester.bestertester',
             'record_mod_datetime': dtstr,
             'record_modifier': 'test:fester.bestertester',
             'record_owner': 'test:fester.bestertester',
             'representations': None,
             'security_mask': 0,
             'url': '',
             'version': '',
             'version_sequence': 0},
            {'base_id': '',
             'cm_authority': 'oid-SProject-0-' + dtiso,
             'comment': u'',
             'create_datetime': dtstr,
             'creator': 'test:fester.bestertester',
             'definition_context': u'',
             'description': u'',
             'frame_of_reference': u'',
             'id': 'Mechanical-Model-2.TFE.' + dtiso,
             'id_ns': 'test',
             'iteration': 0,
             'life_cycle_stage': u'',
             'meta_id': 'Model',
             'mod_datetime': dtstr,
             'modifier': 'test:fester.bestertester',
             'name': u'TFE-Model-2, Version A',
             'oid': 'oid-SModel-1-' + dtiso,
             'owner': 'test:fester.bestertester',
             'record_create_datetime': dtstr,
             'record_creator': 'test:fester.bestertester',
             'record_mod_datetime': dtstr,
             'record_modifier': 'test:fester.bestertester',
             'record_owner': 'test:fester.bestertester',
             'representations': None,
             'security_mask': 0,
             'url': '',
             'version': '',
             'version_sequence': 0},
            {'base_id': '',
             'cm_authority': 'oid-SProject-0-' + dtiso,
             'comment': u'',
             'create_datetime': dtstr,
             'creator': 'test:fester.bestertester',
             'definition_context': u'',
             'description': u'',
             'frame_of_reference': u'',
             'id': 'Mechanical-Model-3.TFE.' + dtiso,
             'id_ns': 'test',
             'iteration': 0,
             'life_cycle_stage': u'',
             'meta_id': 'Model',
             'mod_datetime': dtstr,
             'modifier': 'test:fester.bestertester',
             'name': u'TFE-Model-3, Version A',
             'oid': 'oid-SModel-2-' + dtiso,
             'owner': 'test:fester.bestertester',
             'record_create_datetime': dtstr,
             'record_creator': 'test:fester.bestertester',
             'record_mod_datetime': dtstr,
             'record_modifier': 'test:fester.bestertester',
             'record_owner': 'test:fester.bestertester',
             'representations': None,
             'security_mask': 0,
             'url': '',
             'version': '',
             'version_sequence': 0},
            {'base_id': '',
             'cm_authority': 'oid-SProject-0-' + dtiso,
             'comment': u'',
             'create_datetime': dtstr,
             'creator': 'test:fester.bestertester',
             'definition_context': u'',
             'description': u'',
             'frame_of_reference': u'',
             'id': 'Mechanical-Model-4.TFE.' + dtiso,
             'id_ns': 'test',
             'iteration': 0,
             'life_cycle_stage': u'',
             'meta_id': 'Model',
             'mod_datetime': dtstr,
             'modifier': 'test:fester.bestertester',
             'name': u'TFE-Model-4, Version A',
             'oid': 'oid-SModel-3-' + dtiso,
             'owner': 'test:fester.bestertester',
             'record_create_datetime': dtstr,
             'record_creator': 'test:fester.bestertester',
             'record_mod_datetime': dtstr,
             'record_modifier': 'test:fester.bestertester',
             'record_owner': 'test:fester.bestertester',
             'representations': ['oid-SRepresentation-0-' + dtiso],
             'security_mask': 0,
             'url': '',
             'version': '',
             'version_sequence': 0},
            {'child': None,
             'comment': u'',
             'create_datetime': dtstr,
             'creator': 'test:fester.bestertester',
             'description': u'',
             'id': 'HiFi-MCAD-Model-1.TFE.' + dtiso,
             'id_ns': 'test',
             'meta_id': 'PartModel',
             'mod_datetime': dtstr,
             'modifier': 'test:fester.bestertester',
             'name': u'',
             'oid': 'oid-SPartModel-0-' + dtiso,
             'owner': 'test:fester.bestertester',
             'parent': None,
             'part_model_purpose': u'',
             'record_create_datetime': dtstr,
             'record_creator': 'test:fester.bestertester',
             'record_mod_datetime': dtstr,
             'record_modifier': 'test:fester.bestertester',
             'record_owner': 'test:fester.bestertester',
             'security_mask': 0,
             'url': ''},
            {'child': None,
             'comment': u'',
             'create_datetime': dtstr,
             'creator': 'test:fester.bestertester',
             'description': u'',
             'id': 'HiFi-MCAD-Model-2.TFE.' + dtiso,
             'id_ns': 'test',
             'meta_id': 'PartModel',
             'mod_datetime': dtstr,
             'modifier': 'test:fester.bestertester',
             'name': u'',
             'oid': 'oid-SPartModel-1-' + dtiso,
             'owner': 'test:fester.bestertester',
             'parent': None,
             'part_model_purpose': u'',
             'record_create_datetime': dtstr,
             'record_creator': 'test:fester.bestertester',
             'record_mod_datetime': dtstr,
             'record_modifier': 'test:fester.bestertester',
             'record_owner': 'test:fester.bestertester',
             'security_mask': 0,
             'url': ''},
            {'child': None,
             'comment': u'',
             'create_datetime': dtstr,
             'creator': 'test:fester.bestertester',
             'description': u'',
             'id': 'HiFi-MCAD-Model-3.TFE.' + dtiso,
             'id_ns': 'test',
             'meta_id': 'PartModel',
             'mod_datetime': dtstr,
             'modifier': 'test:fester.bestertester',
             'name': u'',
             'oid': 'oid-SPartModel-2-' + dtiso,
             'owner': 'test:fester.bestertester',
             'parent': None,
             'part_model_purpose': u'',
             'record_create_datetime': dtstr,
             'record_creator': 'test:fester.bestertester',
             'record_mod_datetime': dtstr,
             'record_modifier': 'test:fester.bestertester',
             'record_owner': 'test:fester.bestertester',
             'security_mask': 0,
             'url': ''},
            {'child': None,
             'comment': u'',
             'create_datetime': dtstr,
             'creator': 'test:fester.bestertester',
             'description': u'',
             'id': 'HiFi-MCAD-Model-4.TFE.' + dtiso,
             'id_ns': 'test',
             'meta_id': 'PartModel',
             'mod_datetime': dtstr,
             'modifier': 'test:fester.bestertester',
             'name': u'',
             'oid': 'oid-SPartModel-3-' + dtiso,
             'owner': 'test:fester.bestertester',
             'parent': None,
             'part_model_purpose': u'',
             'record_create_datetime': dtstr,
             'record_creator': 'test:fester.bestertester',
             'record_mod_datetime': dtstr,
             'record_modifier': 'test:fester.bestertester',
             'record_owner': 'test:fester.bestertester',
             'security_mask': 0,
             'url': ''}
            ]
        self.assertEqual(expected, result)

